# Generated by Django 3.0.5 on 2020-04-09 04:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('california', django.db.models.manager.Manager()),
            ],
        ),
    ]
